theme: minima
title: Shrestha Files Blog
author: JPT Games and Apps
email: JPTGamesAndApps@Outlook.Com
description: > # this means to ignore newlines until "baseurl:"
  A blog about File Management in Windows Devices.

# social links
twitter_username: AppsJpt # DO NOT include the @ character, or else the build will fail!
github_username:  JPTGamesAndApps # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
